name: Hermes Watch

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Hermes Check
        run: curl -I -L -A "Mozilla/5.0 (iPhone; CPU iPhone OS 18_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.0 Mobile/15E148 Safari/604.1" "https://www.hermes.com/jp/ja/product/%E3%82%AB%E3%83%BC%E3%83%89%E3%82%B1%E3%83%BC%E3%83%89%E3%82%B9-%E3%80%8A%E3%82%AB%E3%83%AB%E3%83%B4%E3%82%A3%E3%80%8B-%E3%83%87%E3%83%A5%E3%82%AA-%E3%82%B3%E3%83%B3%E3%83%91%E3%82%AF%E3%83%88-H082977CK80/"
